import React from "react"
import { Container } from "@nextui-org/react"
import Head from 'next/head'

export default function DefaultLayout({ children }: { children: React.ReactNode }) {
  return (<Container sm>
    <Head>
      <title>Create Next App</title >
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />

    </Head >
    <style jsx>{`
      .main {
        min - height: 100vh;
        padding: 4rem 0;
        flex: 1;
        display: flex;
        flex-direction: column;
      }`}
    </style>
    <main className="main">
      {children}
    </main>
  </Container >)
}